#!/bin/bash
ip=$1
user=`echo $2 |sed -n 's/@.*//p'`
name=`echo $2 |sed 's/.*@//'`
if [ $user = '']; then
	user='root'
fi
printf "Host $name\n\tHostname $ip\n\tUser $user\n"
case $3 in
	[0-9]*)
		printf "\tPort $3\n"
		;;
esac
printf "\n"
