#!/bin/bash
[ $# -eq 0 ] && { echo "Usage: $0 host user@ipadress port >> .ssh/config
Port is an extra argument and if user@ is missing root@hostname is assumed"; exit 1; }
[ $# -eq 1 ] && { echo "An argument is missing" ; exit 1; }
name=$1
user=`echo $2 |sed -n 's/@.*//p'`
ip=`echo $2 |sed 's/.*@//'`
if [ $user = '']; then
	user='root'
fi
printf "Host $name\n\tHostname $ip\n\tUser $user\n"
case $3 in
	[0-9]*)
		printf "\tPort $3\n"
		;;
esac
printf "\n"
